config/routes.rb
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "silence"
      put "unsilence"
      put "trust_level"
      put "trust_level_lock"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements" => "users#tl3_requirements"
      get "tl3_requirements"
      put "anonymize"
      post "reset_bounce_score"
      put "disable_second_factor"
    end
    get "users/:id.json" => 'users#show', defaults: { format: 'json' }
    get 'users/:id/:username' => 'users#show', constraints: { username: RouteFormat.username }
    get 'users/:id/:username/badges' => 'users#show'
    get 'users/:id/:username/tl3_requirements' => 'users#show'

    post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new
    post "users/invite_admin" => "users#invite_admin", constraints: AdminConstraint.new

    resources :impersonate, constraints: AdminConstraint.new

    resources :email, constraints: AdminConstraint.new do
      collection do
        post "test"
        get "sent"
        get "skipped"
        get "bounced"
        get "received"
        get "rejected"
        get "/incoming/:id/raw" => "email#raw_email"
        get "/incoming/:id" => "email#incoming"
        get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
        get "preview-digest" => "email#preview_digest"
        get "send-digest" => "email#send_digest"
        get "smtp_should_reject"
        post "handle_mail"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
        collection do
          post "roll_up"
        end
      end
      resources :screened_urls,         only: [:index]
      resources :watched_words, only: [:index, :create, :update, :destroy] do
        collection do
          get "action/:id" => "watched_words#index"
        end
      end
      post "watched_words/upload" => "watched_words#upload"
      resources :search_logs,           only: [:index]
      get 'search_logs/term/:term' => 'search_logs#term'
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/themes" => "themes#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
    get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
    put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index", as: 'flags_filtered'
    get "flags/topics/:topic_id" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"

    resources :flagged_topics, constraints: StaffConstraint.new
    resources :themes, constraints: AdminConstraint.new

    post "themes/import" => "themes#import"
    post "themes/upload_asset" => "themes#upload_asset"
    post "themes/generate_key_pair" => "themes#generate_key_pair"
    get "themes/:id/preview" => "themes#preview"

    scope "/customize", constraints: AdminConstraint.new do
      resources :user_fields, constraints: AdminConstraint.new
      resources :emojis, constraints: AdminConstraint.new

      get 'themes/:id/:target/:field_name/edit' => 'themes#index'
      get 'themes/:id' => 'themes#index'

      # They have periods in their URLs often:
      get 'site_texts'             => 'site_texts#index'
      get 'site_texts/:id.json'    => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      get 'site_texts/:id'         => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id.json'    => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id'         => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id.json' => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id'      => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }

      get 'email_templates'          => 'email_templates#index'
      get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
      put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
      delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    get "dashboard" => "dashboard_next#index"
    get "dashboard/general" => "dashboard_next#general"
    get "dashboard/moderation" => "dashboard_next#moderation"

    get "dashboard-old" => "dashboard#index"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        get "keys" => "api#index"
        post "key" => "api#create_master_key"
        put "key" => "api#regenerate_key"
        delete "key" => "api#revoke_key"

        resources :web_hooks
        get 'web_hook_events/:id' => 'web_hooks#list_events', as: :web_hook_events
        get 'web_hooks/:id/events' => 'web_hooks#list_events'
        get 'web_hooks/:id/events/bulk' => 'web_hooks#bulk_events'
        post 'web_hooks/:web_hook_id/events/:event_id/redeliver' => 'web_hooks#redeliver_event'
        post 'web_hooks/:id/ping' => 'web_hooks#ping'
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: RouteFormat.backup }
        put "" => "backups#email", constraints: { id: RouteFormat.backup }
        delete "" => "backups#destroy", constraints: { id: RouteFormat.backup }
        post "restore" => "backups#restore", constraints: { id: RouteFormat.backup }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        delete "cancel" => "backups#cancel"
        post "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_backup_chunk"
        post "upload" => "backups#upload_backup_chunk"
        get "upload_url" => "backups#create_upload_url"
      end
    end

    resources :badges, constraints: AdminConstraint.new do
      collection do
        get "types" => "badges#badge_types"
        post "badge_groupings" => "badges#save_badge_groupings"
        post "preview" => "badges#preview"
      end
    end
  end # admin namespace

  get "email_preferences" => "email#preferences_redirect", :as => "email_preferences_redirect"

  get "email/unsubscribe/:key" => "email#unsubscribe", as: "email_unsubscribe"
  get "email/unsubscribed" => "email#unsubscribed", as: "email_unsubscribed"
  post "email/unsubscribe/:key" => "email#perform_unsubscribe", as: "email_perform_unsubscribe"

  get "extra-locales/:bundle" => "extra_locales#show"

  resources :session, id: RouteFormat.username, only: [:create, :destroy, :become] do
    if !Rails.env.production?
      get 'become'
    end

    collection do
      post "forgot_password"
    end
  end

  get "session/sso" => "session#sso"
  get "session/sso_login" => "session#sso_login"
  get "session/sso_provider" => "session#sso_provider"
  get "session/current" => "session#current"
  get "session/csrf" => "session#csrf"
  get "session/email-login/:token" => "session#email_login"
  post "session/email-login/:token" => "session#email_login"
  get "composer_messages" => "composer_messages#index"
  post "composer/parse_html" => "composer#parse_html"

  resources :static
  post "login" => "static#enter", constraints: { format: /(json|html)/ }
  get "login" => "static#show", id: "login", constraints: { format: /(json|html)/ }
  get "password-reset" => "static#show", id: "password_reset", constraints: { format: /(json|html)/ }
  get "faq" => "static#show", id: "faq", constraints: { format: /(json|html)/ }
  get "guidelines" => "static#show", id: "guidelines", as: 'guidelines', constraints: { format: /(json|html)/ }
  get "rules" => "static#show", id: "rules", as: 'rules', constraints: { format: /(json|html)/ }
  get "tos" => "static#show", id: "tos", as: 'tos', constraints: { format: /(json|html)/ }
  get "privacy" => "static#show", id: "privacy", as: 'privacy', constraints: { format: /(json|html)/ }
  get "signup" => "static#show", id: "signup", constraints: { format: /(json|html)/ }
  get "login-preferences" => "static#show", id: "login", constraints: { format: /(json|html)/ }

  get "my/*path", to: 'users#my_redirect'
  get "user_preferences" => "users#user_preferences_redirect"

  %w{users u}.each_with_index do |root_path, index|
    get "#{root_path}" => "users#index", constraints: { format: 'html' }

    resources :users, except: [:index, :new, :show, :update, :destroy], path: root_path do
      collection do
        get "check_username"
        get "is_local_username"
      end
    end

app/helpers/topics_helper.rb
module TopicsHelper
  include ApplicationHelper

  def render_topic_title(topic)
    link_to(Emoji.gsub_emoji_to_unicode(topic.title), topic.relative_url)
  end

  def categories_breadcrumb(topic)
    breadcrumb = []

    category = topic.category
    if category && !category.uncategorized?
      if (parent = category.parent_category)
        breadcrumb.push url: parent.url, name: parent.name
      end
      breadcrumb.push url: category.url, name: category.name
    end

    Plugin::Filter.apply(:topic_categories_breadcrumb, topic, breadcrumb)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%= html_lang %>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, published_time: @topic_view.published_time) %>
  <% if @topic_view.prev_page %>
    <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
  <% end %>
  <% if @topic_view.next_page %>
    <link rel="next" href="<%= @topic_view.next_page_path -%>">
  <% end %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username %></b> <%= "(#{post.user.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names?) %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<h1>
  <%= render_topic_title(@topic_view.topic) %>
</h1>

<% @breadcrumbs = categories_breadcrumb(@topic_view.topic)
    if @breadcrumbs.present? %>
<div id='breadcrumbs'>
  <% @breadcrumbs.each_with_index do |c,i| %>
    <div id="breadcrumb-<%=i%>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
      <%-if (i+1) < @breadcrumbs.length%>
        itemref="breadcrumb-<%=(i+1)%>"
      <%-end%>>
      <a href="<%=c[:url]%>" itemprop="url">
        <span itemprop="title"><%=c[:name]%></span>
      </a>
    </div>
  <% end %>
</div>
<% end %>

<% if SiteSetting.tagging_enabled %>
  <% @tags = @topic_view.topic.tags %>
  <% if @tags.present? %>
    <div class='tags-list' itemscope itemtype='http://schema.org/ItemList'>
      <% @tags.each do |tag| %>
        <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
          <meta itemprop='url' content='<%= "#{Discourse.base_url}/tags/#{tag.name}" %>'>
          <a href='<%= "#{Discourse.base_url}/tags/#{tag.name}" %>' itemprop='item'>
            <span itemprop='name'><%= tag.name -%></span>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>


<%= server_plugin_outlet "topic_header" %>

<hr>

<%- if include_crawler_content? %>

<% @topic_view.posts.each do |post| %>
  <div itemscope itemtype='http://schema.org/DiscussionForumPosting'>
    <% if (u = post.user) %>
      <div class='creator'>
        <span>
          <a href='<%= Discourse.base_uri %>/u/<%= u.username %>'><b itemprop='author'><%= u.username %></b></a>
           <%= "(#{u.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names? && !u.name.blank?) %>
           <time datetime='<%= post.created_at.to_formatted_s(:iso8601) %>' itemprop='datePublished'>
             <%= post.created_at %>
           </time>
        </span>
        <span itemprop='position'>#<%= post.post_number %></span>
      </div>
      <div class='post' itemprop='articleBody'>
        <%= post.hidden ? t('flagging.user_must_edit').html_safe : post.cooked.html_safe %>
      </div>
      <meta itemprop='interactionCount' content='UserLikes:<%= post.like_count %>'>
      <meta itemprop='interactionCount' content='UserComments:<%= post.reply_count %>'>
      <meta itemprop='headline' content='<%= @topic_view.title %>'>
      <hr>
      <% if @topic_view.link_counts[post.id] && @topic_view.link_counts[post.id].length > 0 %>
        <% @topic_view.link_counts[post.id].each do |link| %>
          <% if link[:reflection] && link[:title].present? %>
            <a href="<%=link[:url]%>"><%=link[:title]%></a>
            <hr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @topic_view.prev_page || @topic_view.next_page %>
  <div role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement'>
    <% if @topic_view.prev_page %>
      <span itemprop='url'><%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev', itemprop: 'name' %></span>
    <% end %>
    <% if @topic_view.next_page %>
      <span itemprop='url'><b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next', itemprop: 'name' %></b></span>
    <% end %>
  </div>
<% end %>

<% end %>

<% content_for :head do %>
  <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, ignore_canonical: true, published_time: @topic_view.published_time) %>

  <% if @topic_view.prev_page || @topic_view.next_page %>
    <% if @topic_view.prev_page %>
      <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
    <% end %>
    <% if @topic_view.next_page %>
      <link rel="next" href="<%= @topic_view.next_page_path -%>">
    <% end %>
  <% end %>
<% end %>

<% content_for(:title) { @title || "#{gsub_emoji_to_unicode(@topic_view.page_title)} - #{SiteSetting.title}" } %>

<% if @topic_view.print %>
  <% content_for :after_body do %>
      <style media="print">
        /* For readability */
        a, a:visited {
          color: #0088cc !important;
        }
      </style>
      <script>
        document.addEventListener("DOMContentLoaded", function() {
          window.print();
        });
      </script>
  <% end %>
<% end %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% topic_url = @topic_view.absolute_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <% if lang %><language><%= lang.sub('_', '-')%></language><% end %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <dc:creator><![CDATA[<%= "@#{post.user.username}#{" #{post.user.name}" if (post.user.name.present? && SiteSetting.enable_names?)}" -%>]]></dc:creator>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <p><%= t('author_wrote', author: link_to("@#{post.user.username}", user_url(post.user.username_lower))).html_safe %></p>
          <blockquote>
            <% if post.hidden %>
              <%= t('flagging.user_must_edit').html_safe %>
            <% else %>
              <%= post.cooked.html_safe %>
            <% end %>
          </blockquote>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false"><%= Discourse.current_hostname %>-post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= topic_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>