config/routes.rb
require "sidekiq/web"
require "mini_scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"
require_dependency "permalink_constraint"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[\w.\-]+?/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do
  relative_url_root = (defined?(Rails.configuration.relative_url_root) && Rails.configuration.relative_url_root) ? Rails.configuration.relative_url_root + '/' : '/'

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  post "webhooks/mailgun"  => "webhooks#mailgun"
  post "webhooks/sendgrid" => "webhooks#sendgrid"
  post "webhooks/mailjet"  => "webhooks#mailjet"
  post "webhooks/mandrill" => "webhooks#mandrill"
  post "webhooks/sparkpost" => "webhooks#sparkpost"

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    # only allow sidekiq in master site
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new(require_master: true)
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  resources :about do
    collection do
      get "live_post_counts"
    end
  end

  get "finish-installation" => "finish_installation#index"
  get "finish-installation/register" => "finish_installation#register"
  post "finish-installation/register" => "finish_installation#register"
  get "finish-installation/confirm-email" => "finish_installation#confirm_email"
  put "finish-installation/resend-email" => "finish_installation#resend_email"

  resources :directory_items

  get "site" => "site#site"
  namespace :site do
    get "settings"
    get "custom_html"
    get "banner"
    get "emoji"
  end

  get "site/basic-info" => 'site#basic_info'
  get "site/statistics" => 'site#statistics'
  get "site/selectable-avatars" => "site#selectable_avatars"

  get "srv/status" => "forums#status"

  get "wizard" => "wizard#index"
  get "wizard/qunit" => "wizard#qunit"
  get 'wizard/steps' => 'steps#index'
  get 'wizard/steps/:id' => "wizard#index"
  put 'wizard/steps/:id' => "steps#update"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    get 'plugins' => 'plugins#index'

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports" => "reports#index"
    get "reports/bulk" => "reports#bulk"
    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        get 'bulk'
        get 'bulk-complete' => 'groups#bulk'
        put 'bulk' => 'groups#bulk_perform'
      end
      member do
        put "owners" => "groups#add_owners"
        delete "owners" => "groups#remove_owner"
      end
    end

    get "groups/:type" => "groups#show", constraints: AdminConstraint.new
    get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

    get "moderation_history" => "moderation_history#index"

    resources :users, id: RouteFormat.username, except: [:show] do
      collection do
        get "list" => "users#index"
        get "list/:query" => "users#index"
        get "ip-info" => "users#ip_info"
        delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
        get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      delete "penalty_history", constraints: AdminConstraint.new
      put "suspend"
      put "delete_all_posts"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "silence"
      put "unsilence"
      put "trust_level"
      put "trust_level_lock"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements" => "users#tl3_requirements"
      get "tl3_requirements"
      put "anonymize"
      post "reset_bounce_score"
      put "disable_second_factor"
    end
    get "users/:id.json" => 'users#show', defaults: { format: 'json' }
    get 'users/:id/:username' => 'users#show', constraints: { username: RouteFormat.username }
    get 'users/:id/:username/badges' => 'users#show'
    get 'users/:id/:username/tl3_requirements' => 'users#show'

    post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new
    post "users/invite_admin" => "users#invite_admin", constraints: AdminConstraint.new

    resources :impersonate, constraints: AdminConstraint.new

    resources :email, constraints: AdminConstraint.new do
      collection do
        post "test"
        get "sent"
        get "skipped"
        get "bounced"
        get "received"
        get "rejected"
        get "/incoming/:id/raw" => "email#raw_email"
        get "/incoming/:id" => "email#incoming"
        get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
        get "preview-digest" => "email#preview_digest"
        get "send-digest" => "email#send_digest"
        get "smtp_should_reject"
        post "handle_mail"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
        collection do
          post "roll_up"
        end
      end
      resources :screened_urls,         only: [:index]
      resources :watched_words, only: [:index, :create, :update, :destroy] do
        collection do
          get "action/:id" => "watched_words#index"
        end
      end
      post "watched_words/upload" => "watched_words#upload"
      resources :search_logs,           only: [:index]
      get 'search_logs/term/:term' => 'search_logs#term'
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/themes" => "themes#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
    get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
    put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index", as: 'flags_filtered'
    get "flags/topics/:topic_id" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"

    resources :flagged_topics, constraints: StaffConstraint.new
    resources :themes, constraints: AdminConstraint.new

    post "themes/import" => "themes#import"
    post "themes/upload_asset" => "themes#upload_asset"
    post "themes/generate_key_pair" => "themes#generate_key_pair"
    get "themes/:id/preview" => "themes#preview"

    scope "/customize", constraints: AdminConstraint.new do
      resources :user_fields, constraints: AdminConstraint.new
      resources :emojis, constraints: AdminConstraint.new

      get 'themes/:id/:target/:field_name/edit' => 'themes#index'
      get 'themes/:id' => 'themes#index'

      # They have periods in their URLs often:
      get 'site_texts'             => 'site_texts#index'
      get 'site_texts/:id.json'    => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      get 'site_texts/:id'         => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id.json'    => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/:id'         => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id.json' => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/:id'      => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }

      get 'email_templates'          => 'email_templates#index'
      get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
      put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
      delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    get "dashboard" => "dashboard_next#index"
    get "dashboard/general" => "dashboard_next#general"
    get "dashboard/moderation" => "dashboard_next#moderation"

    get "dashboard-old" => "dashboard#index"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

app/models/about.rb
class About
  include ActiveModel::Serialization
  include StatsCacheable

  attr_accessor :moderators,
                :admins

  def self.stats_cache_key
    'about-stats'
  end

  def self.fetch_stats
    About.new.stats
  end

  def version
    Discourse::VERSION::STRING
  end

  def https
    SiteSetting.force_https
  end

  def title
    SiteSetting.title
  end

  def locale
    SiteSetting.default_locale
  end

  def description
    SiteSetting.site_description
  end

  def moderators
    @moderators ||= User.where(moderator: true, admin: false)
      .human_users
      .order(:username_lower)
  end

  def admins
    @admins ||= User.where(admin: true).human_users.order(:username_lower)
  end

  def stats
    @stats ||= {
       topic_count: Topic.listable_topics.count,
       post_count: Post.count,
       user_count: User.real.count,
       topics_7_days: Topic.listable_topics.where('created_at > ?', 7.days.ago).count,
       topics_30_days: Topic.listable_topics.where('created_at > ?', 30.days.ago).count,
       posts_7_days: Post.where('created_at > ?', 7.days.ago).count,
       posts_30_days: Post.where('created_at > ?', 30.days.ago).count,
       users_7_days: User.where('created_at > ?', 7.days.ago).count,
       users_30_days: User.where('created_at > ?', 30.days.ago).count,
       active_users_7_days: User.where('last_seen_at > ?', 7.days.ago).count,
       active_users_30_days: User.where('last_seen_at > ?', 30.days.ago).count,
       like_count: UserAction.where(action_type: UserAction::LIKE).count,
       likes_7_days: UserAction.where(action_type: UserAction::LIKE).where("created_at > ?", 7.days.ago).count,
       likes_30_days: UserAction.where(action_type: UserAction::LIKE).where("created_at > ?", 30.days.ago).count
    }
  end

end

app/controllers/about_controller.rb
require_dependency 'rate_limiter'

class AboutController < ApplicationController

  requires_login only: [:live_post_counts]

  skip_before_action :check_xhr, only: [:index]

  def index
    return redirect_to path('/login') if SiteSetting.login_required? && current_user.nil?

    @about = About.new
    respond_to do |format|
      format.html do
        render :index
      end
      format.json do
        render_serialized(@about, AboutSerializer)
      end
    end
  end

  def live_post_counts
    RateLimiter.new(current_user, "live_post_counts", 1, 10.minutes).performed! unless current_user.staff?
    category_topic_ids = Category.pluck(:topic_id).compact!
    public_topics = Topic.listable_topics.visible.secured(Guardian.new(nil)).where.not(id: category_topic_ids)
    stats = { public_topic_count: public_topics.count }
    stats[:public_post_count] = public_topics.sum(:posts_count) - stats[:public_topic_count]
    render json: stats
  end
end

app/views/about/index.html.erb
<% if crawler_layout? %>

<% content_for :title do %><%=t "about" %> - <%= SiteSetting.title %><% end %>

<section itemscope itemtype="https://schema.org/AboutPage">
  <h1 itemprop="name">
    <%=t "js.about.title", {title: @about.title} %>
  </h1>

  <div itemprop="text">
    <%= @about.description %>
  </div>

  <h2><%=t "js.about.our_admins" %></h2>

  <div class='admins-list' itemscope itemtype='http://schema.org/ItemList'>
    <% @about.admins.each do |user| %>
      <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
        <meta itemprop='url' content='<%= user_path(user) %>'>
        <a href='<%= user_path(user) %>' itemprop='item'>
          <span itemprop='image'>
            <img width="45" height="45" class="avatar" src="<%= user.small_avatar_url %>">
          </span>
          <span itemprop='name'>
            <%= user.username %>
            <% if user.name.present? && SiteSetting.enable_names %>
              - <%= user.name %>
            <% end %>
          </span>
        </a>
      </div>
    <% end %>
  </div>

  <% if @about.moderators.count > 0 %>
    <h2><%=t "js.about.our_moderators" %></h2>
    <div class='moderators-list' itemscope itemtype='http://schema.org/ItemList'>
      <% @about.moderators.each do |user| %>
        <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
          <meta itemprop='url' content='<%= user_path(user) %>'>
          <a href='<%= user_path(user) %>' itemprop='item'>
            <span itemprop='image'>
              <img width="45" height="45" class="avatar" src="<%= user.small_avatar_url %>">
            </span>
            <span itemprop='name'>
              <%= user.username %>
              <% if user.name.present? && SiteSetting.enable_names %>
                - <%= user.name %>
              <% end %>
            </span>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>

  <%- stats = About.fetch_cached_stats %>

  <section class='about stats'>
    <h2><%=t 'js.about.stats' %></h2>

    <table class='table'>
      <tr>
        <th>&nbsp;</th>
        <th><%=t 'js.about.stat.all_time' %></th>
        <th><%=t 'js.about.stat.last_7_days' %></th>
        <th><%=t 'js.about.stat.last_30_days' %></th>
      </tr>
      <tr>
        <td class='title'><%=t 'js.about.topic_count' %></td>
        <td><%= stats["topic_count"] %></td>
        <td><%= stats["topics_7_days"] %></td>
        <td><%= stats["topics_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.post_count' %></td>
        <td><%= stats["post_count"] %></td>
        <td><%= stats["posts_7_days"] %></td>
        <td><%= stats["posts_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.user_count' %></td>
        <td><%= stats["user_count"] %></td>
        <td><%= stats["users_7_days"] %></td>
        <td><%= stats["users_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.active_user_count' %></td>
        <td>&mdash;</td>
        <td><%= stats["active_users_7_days"] %></td>
        <td><%= stats["active_users_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.like_count' %></td>
        <td><%= stats["like_count"] %></td>
        <td><%= stats["likes_7_days"] %></td>
        <td><%= stats["likes_30_days"] %></td>
      </tr>
    </table>
  </section>

</section>
<br/>
<br/>

<% end %>

<% content_for :head do %>
  <%= raw crawlable_meta_data(title: SiteSetting.title, description: SiteSetting.site_description) %>
<% end %>